### ISSUE TITLE
Question about additional deps

### ISSUE THREAD

**Issue by sneridagh** [plone/volto-addon-ci#2]
@avoinea Why `jest-transform-stub` is required again?
https://github.com/plone/volto-addon-ci/blob/0d4e8c752619b8b1cb235368679decac0f0fa5cb/docker-entrypoint.sh#L75

also, if you were to add `jest-unit`somewhere you would do it in Volto core or in the add ons?

**Comment by avoinea** [comment]
@sneridagh Don't remember, I think @valentinab25 added. Within the package description it says:

```
Jest doesn't handle non JavaScript assets by default.
You can use this module to avoid errors when importing non JavaScript assets.
```

**Comment by valentinab25** [comment]
I think we can remove it, we are not using it anymore, looks like we are now using jest-css-modules for the same purpose

**Comment by sneridagh** [comment]
@avoinea I think so, Volto should provide them, and if not, we should. Anyways I think we are good if we remove them.

**Comment by wesleybl** [comment]
@sneridagh these dependencies were removed in alpha branch, but not in others. Is this enough to close this issue?

**Comment by sneridagh** [comment]
I'd say so! btw, I'm now using `@plone/scripts` addon command for testing Volto add-ons.

https://training.plone.org/effective-volto/testing/addons.html?highlight=plone%20scripts#plone-scripts
https://github.com/plone/volto/blob/master/packages/scripts/README.md#addon

**Comment by wesleybl** [comment]
@sneridagh Interesting! It does not use symlinks, which avoids problems in test execution, since jest does not follow symlinks.
